import { PagesDesktopPath, PagesMobilePath, MetaInterface, RouterRegisterName, RouterLoginName, RouterHomeIndexName } from 'src/router';

export const DefaultTemplateName = 'default'

export const defaultRouter = [
  {
    name: 'Layouts',
    path: '/',
    component: '/src/layouts/main.vue',
    meta: {},
    children: [
        {
          name: RouterHomeIndexName,
          path: '/',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'home.vue'), meta: {} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'home.vue'), meta: {footer: true} as MetaInterface},
          children: [],
        },
        {
          name: RouterLoginName,
          path: '/login',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'home.vue'), meta: {} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'login.vue'), meta: {} as MetaInterface},
          children: [],
        },
        {
          name: RouterRegisterName,
          path: '/register',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'home.vue'), meta: {} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'register.vue'), meta: {} as MetaInterface},
          children: [],
        },
        {
          name: 'ProductMarkets',
          path: '/markets',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'markets.vue'), meta: {} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'markets.vue'), meta: {footer: true} as MetaInterface},
          children: [],
        },
        {
          name: 'ProductFutures',
          path: '/futures',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'product/futures.vue'), meta: {} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'product/futures.vue'), meta: {footer: true} as MetaInterface},
          children: [],
        },
        {
          name: 'ProductContract',
          path: '/contract',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'product/contract.vue'), meta: {} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'product/contract.vue'), meta: {footer: true} as MetaInterface},
          children: [],
        },
        {
          name: 'UserIndex',
          path: '/users',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'home.vue'), meta: {requireAuth:true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'users/index.vue'), meta: {requireAuth:true,footer: true} as MetaInterface},
          children: [],
        },
        {
          name: 'ArticleIndex',
          path: '/article',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'article/index.vue'), meta: {} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'article/index.vue'), meta: {header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'DownloadIndex',
          path: '/download',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'download.vue'), meta: {} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'download.vue'), meta: {header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'LangIndex',
          path: '/lang',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'home.vue'), meta: {} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'lang.vue'), meta: {header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'HelpersIndex',
          path: '/helpers',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'helpers.vue'), meta: {} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'helpers.vue'), meta: {header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'InviteIndex',
          path: '/users/team/invite',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'users/team/invite.vue'), meta: {requireAuth:true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'users/team/invite.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'UserSetting',
          path: '/users/setting',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'users/setting/index.vue'), meta: {requireAuth:true,drawerLeft: true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'users/setting/info.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'SettingsIndex',
          path: '/settings',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'users/setting/index.vue'), meta: {requireAuth:true,drawerLeft: true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'users/setting/index.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'UserUpdatePassword',
          path: '/users/setting/update/password',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'users/setting/index.vue'), meta: {requireAuth:true,drawerLeft: true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'users/setting/password.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'UserUpdateSecretKey',
          path: '/users/setting/update/secret',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'users/setting/index.vue'), meta: {requireAuth:true,drawerLeft: true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'users/setting/secretKey.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'UserAuthIndex',
          path: '/users/auth',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'users/auth.vue'), meta: {requireAuth:true,drawerLeft: true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'users/auth.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'UserLevelIndex',
          path: '/users/level',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'users/level.vue'), meta: {requireAuth:true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'users/level.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'TeamIndex',
          path: '/users/team',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'users/team/index.vue'), meta: {requireAuth:true,drawerLeft: true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'users/team/index.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'TeamDetailsIndex',
          path: '/users/team/earnings',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'users/team/details.vue'), meta: {requireAuth:true,drawerLeft: true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'users/team/details.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },

        {
          name: 'WalletsAccountIndex',
          path: '/wallets/account',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'wallets/account/index.vue'), meta: {requireAuth:true,drawerLeft: true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'wallets/account/index.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'WalletsAccountUpdate',
          path: '/wallets/account/update',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'wallets/account/update.vue'), meta: {requireAuth:true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'wallets/account/update.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'WalletsDeposit',
          path: '/wallets/deposit',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'wallets/deposit.vue'), meta: {requireAuth:true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'wallets/deposit.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'WalletsWithdraw',
          path: '/wallets/withdraw',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'wallets/withdraw.vue'), meta: {requireAuth:true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'wallets/withdraw.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'WalletsIndex',
          path: '/wallets',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'wallets/index.vue'), meta: {requireAuth:true,drawerLeft: true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'wallets/index.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'WalletsBill',
          path: '/wallets/bill',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'wallets/bill.vue'), meta: {requireAuth:true,drawerLeft: true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'wallets/bill.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'WalletsAssetsDetails',
          path: '/wallets/assets/details',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'wallets/assets/details.vue'), meta: {requireAuth:true,drawerLeft: true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'wallets/assets/details.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'WalletsAssets',
          path: '/wallets/assets',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'wallets/assets/index.vue'), meta: {requireAuth:true,drawerLeft: true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'wallets/assets/index.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'WalletsTransferRecord',
          path: '/wallets/transfer/record',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'wallets/transfer/index.vue'), meta: {requireAuth:true,drawerLeft: true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'wallets/transfer/index.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'WalletsTransferCreate',
          path: '/wallets/transfer',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'wallets/transfer/create.vue'), meta: {requireAuth:true,drawerLeft: true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'wallets/transfer/create.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'WalletsConvertRecord',
          path: '/wallets/convert/record',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'wallets/convert/index.vue'), meta: {requireAuth:true,drawerLeft: true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'wallets/convert/index.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
        {
          name: 'WalletsConvertCreate',
          path: '/wallets/convert',
          desktop: {component: PagesDesktopPath(DefaultTemplateName,'wallets/convert/create.vue'), meta: {requireAuth:true,drawerLeft: true} as MetaInterface},
          mobile: {component: PagesMobilePath(DefaultTemplateName, 'wallets/convert/create.vue'), meta: {requireAuth:true,header: true} as MetaInterface},
          children: [],
        },
      ],
  },
];
